jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            configuration-database:
                namespace_prefix: "App\\Entity"
                path: "%kernel.root_dir%/Resources/config/serializer"
