# Api Entry Point
api_entrypoint:
    path:     /
    controller: App\Action\EntryPoint

# Categories
categories:
    resource: ./actions/categories.yaml
    name_prefix: api_
    prefix: api/v1/categories
